### Site metadata ###

site_name: Golang Reference
site_description: 'Go Lang tutorial with examples'
site_url: https://rmechi.github.io

repo_url: https://github.com/rmechi/go
edit_uri: edit/master/docs/docs

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
use_directory_urls: false
extra_css: [style.css]
markdown_extensions:
  - toc:
      permalink: "#"


nav:
  - Home: index.md
  - Tutorial:
      - Arrays: go/arrays.md
      - Slices: go/slices.md
      - GoMaps: go/maps.md

